require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - vendor/**/*
    - log/**/*
    - tmp/**/*
    - db/schema.rb

Lint/ScriptPermission:
  Include:
    - bin/**/*

RSpec/FilePath:
  Exclude:
    - spec/graphql/**/*

RSpec/MultipleMemoizedHelpers:
  Max: 8

Style/Documentation:
  Exclude:
    - config/application.rb
    - app/models/application_record.rb
    - spec/**/*
    - test/**/*
    - db/migrate/*
    - app/graphql/*_schema.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 16

Metrics/ClassLength:
  Exclude:
    - rspec/**/*

Metrics/PerceivedComplexity:
  Max: 9

Layout/LineLength:
  Max: 198

Metrics/BlockLength:
  Max: 25
  Exclude:
    - Guardfile
    - spec/**/*
