---
version: "3.8"
services:
  postgres:
    image: postgis/postgis:13-master
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DBNAME: postgres
    volumes:
    - type: bind
      source: ./db/setup-db.sql
      target: /docker-entrypoint-initdb.d/setup-db.sql
